/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package seman8;

import java.sql.Connection;
import java.awt.BorderLayout;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Inter extends javax.swing.JFrame {
    
    public Inter() {
        initComponents();
        this.setLocationRelativeTo(null);
        Connection conex= (Connection) BaseDatos.getIntancia().getConexion();
        if(conex!=null){
            JOptionPane.showMessageDialog(null, "Conexion exitosa con la base de datos", "", JOptionPane.INFORMATION_MESSAGE );
        }else{
            JOptionPane.showMessageDialog(null, "Error con la conexion a la base de datos", "", JOptionPane.ERROR_MESSAGE );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        Contenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        btn_Consulta = new javax.swing.JMenuItem();
        CrearProducto = new javax.swing.JMenuItem();
        btn_actualizar = new javax.swing.JMenuItem();
        btn_Delate = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        ConsultarVenta = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jMenu2.setLabel("Productos");

        btn_Consulta.setText("Consultar Productos");
        btn_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultaActionPerformed(evt);
            }
        });
        jMenu2.add(btn_Consulta);

        CrearProducto.setText("Crear Producto");
        CrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearProductoActionPerformed(evt);
            }
        });
        jMenu2.add(CrearProducto);

        btn_actualizar.setText("Actualizar Producto");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jMenu2.add(btn_actualizar);

        btn_Delate.setText("Eliminar Producto");
        btn_Delate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelateActionPerformed(evt);
            }
        });
        jMenu2.add(btn_Delate);

        jMenuBar1.add(jMenu2);

        jMenu3.setLabel("Ventas");

        jMenuItem5.setText("Registrar Venta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        ConsultarVenta.setText("Consultar Venta");
        ConsultarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarVentaActionPerformed(evt);
            }
        });
        jMenu3.add(ConsultarVenta);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProductoActionPerformed
        Procreate create=new Procreate();
        create.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        create.setLocation(0,0);
        
        Contenedor.removeAll();
        Contenedor.add(create, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
        
    }//GEN-LAST:event_CrearProductoActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        ProUpdate update=new ProUpdate();
        update.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        update.setLocation(0,0);
        
        Contenedor.removeAll();
        Contenedor.add(update, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_DelateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelateActionPerformed
        ProDelate Delate=new ProDelate();
        Delate.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        Delate.setLocation(0,0);
        
        Contenedor.removeAll();
        Contenedor.add(Delate, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_btn_DelateActionPerformed

    private void btn_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultaActionPerformed
        ProConsulta Consulta=new ProConsulta();
        Consulta.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        Consulta.setLocation(0,0);
        
        Contenedor.removeAll();
        Contenedor.add(Consulta, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_btn_ConsultaActionPerformed

    private void ConsultarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarVentaActionPerformed
        VenConsultar Consulta=new VenConsultar();
        Consulta.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        Consulta.setLocation(0,0);
        
        Contenedor.removeAll();
        Contenedor.add(Consulta, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_ConsultarVentaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
        VenVentas Consulta = new VenVentas();
        Consulta.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        Consulta.setLocation(0,0);
        
        Contenedor.removeAll();
        Contenedor.add(Consulta, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsultarVenta;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JMenuItem CrearProducto;
    private javax.swing.JMenuItem btn_Consulta;
    private javax.swing.JMenuItem btn_Delate;
    private javax.swing.JMenuItem btn_actualizar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
